packages:
  - packages/*
  - examples/*

catalog:
  '@jest/globals': ^30.0.0
  '@types/node': ^22.15.30
  jest: ^30.0.0
  rimraf: ^6.0.1
  ts-jest: ^29.4.0
  ts-node: ^10.9.2
  typescript: 5.8.3
  jest-mock-extended: ^4.0.0
