name: On Push Main

on:
  push:
    branches:
      - main

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup volta
        uses: volta-cli/action@v4
      - name: Install node and pnpm
        run: volta install node pnpm
      - name: Run tests
        run: pnpm run test
      - name: Create build
        run: pnpm run build