name: On Pull Request

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup volta
        uses: volta-cli/action@v4
      - name: Install node and pnpm
        run: volta install node pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Run lint
        run: pnpm run lint

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup volta
        uses: volta-cli/action@v4
      - name: Install node and pnpm
        run: volta install node pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Create build
        run: pnpm run build
      - name: Run tests
        run: pnpm run test
